Repository HackathonTeam05/Guardian, pull requests merged in 2023-05, with the labels that each got.

#10 feat: create button i#2
  src/App.tsx
  src/components/Button.tsx
  src/stories/Button.stories.ts
  src/stories/Header.tsx
  src/stories/button.css
Labels: enhancement

#12 feat: add Image component
  src/components/Image.tsx
Labels: enhancement

#15 fix: cleanup unnecessary files
  index.html
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
Labels: enhancement

#24 feat: Criado pasta backend e instalado dependencias
  backend/.gitignore
  backend/config/database.js
  backend/package-lock.json
  backend/package.json
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/LICENSE
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Image.tsx
  frontend/src/main.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/header.css
  frontend/src/stories/page.css
  frontend/src/styles.css
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement

#18 feat: create input component
  src/components/Input.tsx
Labels: enhancement

#26 feat: Create introduction.mdx in stories
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: documentation, enhancement

#34 I#29
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button.tsx
  frontend/src/components/Image.tsx
  frontend/src/components/ThemeToggleButton.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Image.stories.ts
  frontend/src/stories/Input.stories.ts
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/LoginPage.stories.ts
  frontend/src/stories/ThemeToggleButton.stories.ts
  frontend/tailwind.config.js
Labels: documentation, enhancement

#43 feat: Create alertcomponent and stories
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AlertMessage.tsx
  frontend/src/stories/AlertMessage.stories.ts
Labels: documentation, enhancement

#46 I#45 Server js in backend
  backend/config/database.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/vercel.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Calendar.tsx
  frontend/src/stories/Calendar.stories.ts
Labels: enhancement

#49 feat: create route users
  backend/.gitignore
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/src/index.js
  frontend/package.json
Labels: enhancement

#54 feat: create database and first datas
  backend/src/index.js
Labels: enhancement

#77 feat: create shared file and first test
  shared/.gitignore
  shared/main.js
  shared/main.spec.js
  shared/package-lock.json
  shared/package.json
  shared/style.css
Labels: enhancement

#81 I#44 Create Calendar component
  backend/src/index.js
  backend/src/routes/delete.js
  backend/src/routes/get.js
  backend/src/routes/post.js
  backend/src/routes/put.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Calendar.tsx
  frontend/src/pages/EasyRoomPage.tsx
  frontend/src/stories/Calendar.stories.ts
Labels: documentation, enhancement

#92 I#78 Create All Routes
  backend/package.json
  backend/src/index.js
  backend/src/routes/company.js
  backend/src/routes/delete.js
  backend/src/routes/get.js
  backend/src/routes/post.js
  backend/src/routes/put.js
  backend/src/routes/reservation.js
  backend/src/routes/room.js
  backend/src/routes/users.js
  frontend/src/components/EasyRoomPage.tsx
  frontend/src/components/Image.tsx
Labels: enhancement

#19 README.md
  README.md
Labels: documentation

#95 feat: create README Frontend i#51
  frontend/README.md
Labels: enhancement

#107 feat: Create validatelogin and validateemailuser
  backend/src/index.js
  backend/src/routes/users.js
Labels: enhancement

#110 Update Frontend README
  frontend/README.html
  frontend/README.md
  img/Logo.png:Zone.Identifier
  img/backend.png
  img/backend.png:Zone.Identifier
  img/frontend.png
  img/frontend.png:Zone.Identifier
  img/test.png
Labels: documentation

#109 bug: Resolve easy interface
  backend/src/index.js
  frontend/src/App.tsx
  frontend/src/components/Calendar.tsx
  frontend/src/images/easylogo.svg
  frontend/src/pages/EasyRoomPage.tsx
Labels: bug

#111 Update Backend README
  backend/README.md
Labels: documentation

#113 fix: correct database routes backend and api
  backend/src/index.js
  backend/src/routes/companies.js
  backend/src/routes/reservations.js
  backend/src/routes/rooms.js
  backend/src/routes/users.js
  frontend/src/pages/EasyRoomPage.tsx
Labels: bug
